version: '3'


services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    expose:
      - "80"
    ports:
      - 8081:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
    ## --------------------------------------------
    ## | 4 : database server
    ## --------------------------------------------
  redisdb:
    image: redis:4.0.10-alpine
    expose:
      - "6379"
    ports:
      - 6379:6379
